[package]
name = "bevy_layout_ui"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.2"
bytemuck = { version = "1.15.0", features = ["derive"] }

[dev-dependencies]
bevy-inspector-egui = "0.24.0"
